### ISSUE TITLE
External connection failed

### ISSUE THREAD

**Issue by thedancebear** [kicker22004/BSCC-MC-Edition#1]
Hello together,
i installed bscc on my raspberry pi 3 and started a SPIGOT Server 1.9.2
The port 25565 is free, i checked this with canyouseeme.org
I looked for my external IP (called WAN ip) and gave this to my friends, but they cant connect!
I can connect my server via the intern IP (192.168......) My friends via external IpV4 (WAN) IP cant connect (xxxx.xxx.xxx.xxx:25565)
Whats wrong here ? I dont know how to fix that, and the internet dont tell me the answer.
Thank you

**Comment by kicker22004** [comment]
Ok first they don't need to add the port at the end if it's the default port, also have you tested connecting with your external ip??. And last are they running a cracked version of Minecraft? If so you need to change a server properties option ( online-mode=true to online-mode=false ). Those are usually the issues. Can they connect to a vanilla server? Good luck

**Comment by thedancebear** [comment]
It works! It works :) thank you kicker22004 :).
Just one more question: when the server loads new chucks all player get a few secons lag, so for example you cant hit a pig.
I set the RAM for MC-Server to 800mb in the conf.cfg you know what to do for no lags ? 
thank you :)

**Comment by kicker22004** [comment]
The lag can be for many reasons, including hardware and if you pre-loaded the server or not. There is a lot of information about this on the internet so i'll be closing this issue as it doesn't pertain to the Project. I'm glad you got it working tho. Enjoy.
