### ISSUE TITLE
Spigot selection does not seem to work right now

### ISSUE THREAD

**Issue by eison** [kicker22004/BSCC-MC-Edition#4]

**Comment by eison** [comment]
Sorry forgot to put issue.
On the pull from web the himalaya command is not found.
The install put a node-module in usr/bin
not sure what to do.

**Comment by eison** [comment]
Sorry forgot to put issue.
On the pull from web the himalaya command is not found.
The install put a node-module in usr/bin
not sure what to do.

**Comment by kicker22004** [comment]
> Sorry forgot to put issue.
> On the pull from web the himalaya command is not found.
> The install put a node-module in usr/bin
> not sure what to do.

Sorry I stepped away from this project some time ago.
I'm currently revisiting it and making updates to the code and will probably be removing spigot for Sponge as it's probably the better option at this time.
