### ISSUE TITLE
no eula.txt file

### ISSUE THREAD

**Issue by Seregag** [kicker22004/BSCC-MC-Edition#5]
When installing Vanilla writes at the end "Something is wrong here, there is no eula.txt file to be found."

**Comment by markstinson** [comment]
I had the same problem using Mojang's Vanilla 1.13.2 (I saw the loop having configured it for debug). Opening a second terminal, I `touch /opt/BSCC/minecraft_server/eula.txt` -- then the setup continued.

I went back afterwards and edited the eula.txt to contain "eula=true" just in case to avoid any forthcoming issues.

**Comment by kicker22004** [comment]
Thank you @markstinson for helping @Seregag. This was always a home project but always wanted to expand the project. Thanks for assisting him.
